package tplsql

import (
	_ "github.com/go-sql-driver/mysql"
)

var _sql = `-- Code generated by "grm gen sql"; DO NOT EDIT.
{{range .}}

{{"{{"}}define "{{.Name}}"{{"}}"}}
-- @Type {{.Type}}
-- @Comm "{{.Comm}}"
{{range .Parameter}}-- {{.Method}} {{.Name}} {{.Type}} {{.Tags}} "{{.Comm}}"
{{end}}
{{.Sql}}

{{"{{end}}"}}

{{end}}
`

type DefinesTplData struct {
	Type      string
	Comm      string
	Name      string
	Sql       string
	Parameter []*ParameterTplData
}

type ParameterTplData struct {
	Method    string
	Name      string
	OriAsName string
	OriName   string
	Type      string
	Tags      string
	Comm      string
}
